export const CALC_DOCUMENTS_AMOUNT = 'CALC_DOCUMENTS_AMOUNT';

export const HANDLE_REQUEST_ERROR = 'HANDLE_REQUEST_ERROR';
export const HANDLE_REQUEST_SUCCESS = 'HANDLE_REQUEST_SUCCESS';
export const CLOSE_BANNER = 'CLOSE_BANNER';
export const CONTROL_LOADING = 'CONTROL_LOADING';
export const OPEN_MODAL_WITH_DETAIL = 'OPEN_MODAL_WITH_DETAIL';
export const CLOSE_MODAL_WITH_DETAIL = 'CLOSE_MODAL_WITH_DETAIL';

